In [1]:
import numpy as np
import re
import nltk
from sklearn.datasets import load_files
# nltk.download('stopwords')
import pickle
from nltk.corpus import stopwords

<frozen importlib._bootstrap>:219: RuntimeWarning: scipy._lib.messagestream.MessageStream size changed, may indicate binary incompatibility. Expected 56 from C header, got 64 from PyObject


In [2]:
phoenix_dataset = load_files(r"C:/Users/eklav/Phoenix 98DocType/TextClassificationFromTextFile")
X, y = phoenix_dataset.data, phoenix_dataset.target

In [3]:
documents = []

from nltk.stem import WordNetLemmatizer

stemmer = WordNetLemmatizer()

for sen in range(0, len(X)):
    # Remove all the special characters
    document = re.sub(r'\W', ' ', str(X[sen]))
    
    # remove all single characters
    document = re.sub(r'\s+[a-zA-Z]\s+', ' ', document)
    
    # Remove single characters from the start
    document = re.sub(r'\^[a-zA-Z]\s+', ' ', document) 
    
    # Substituting multiple spaces with single space
    document = re.sub(r'\s+', ' ', document, flags=re.I)
    
    # Removing prefixed 'b'
    document = re.sub(r'^b\s+', '', document)
    
    # Converting to Lowercase
    document = document.lower()
    
    # Lemmatization
    document = document.split()

    document = [stemmer.lemmatize(word) for word in document]
    document = ' '.join(document)
    
    documents.append(document)

In [10]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer(max_features=1500, min_df=5, max_df=0.7, stop_words=stopwords.words('english'))
X = vectorizer.fit_transform(documents).toarray()

In [5]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidfconverter = TfidfTransformer()
X = tfidfconverter.fit_transform(X).toarray()

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)
print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))

8999
6000
8999
6000


In [7]:
from sklearn.naive_bayes import MultinomialNB
clsfy = MultinomialNB().fit(X_train, y_train)

In [8]:
y_pred = clsfy.predict(X_test)

In [9]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[  0   0   0   0   0   0   0   0   0   2   0   0]
 [  0 630   0   0   0   0   0   2   0   0   0   6]
 [  0   0 489   3   0   0   5   2   2  12  97   0]
 [  0   0   2 583   0   0   0   3   0   2   0   0]
 [  0   1   0   0 131 110   0  18   0   0   0   1]
 [  0   1   0   2  61 503   0  11   0   0   0   1]
 [  0   0  20   1   0   0 574   3   0   2   2   0]
 [  0   2   4   5  10  10   1 513   2   3  23   2]
 [  0   0   0   1   0   0   0   0 441   0   0   0]
 [  0   0  12   0   0   0   6   0   0 401  53   0]
 [  0   0   9   6   0   2   1   5   4  10 584   0]
 [  0  11   0   0   1   0   0   3   0   1   2 590]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       0.98      0.99      0.98       638
           2       0.91      0.80      0.85       610
           3       0.97      0.99      0.98       590
           4       0.65      0.50      0.56       261
           5       0.80      0.87      0.84       579
        

C:\Users\eklav\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\eklav\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\eklav\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [10]:
# with open('BayesClassification_text_classifier', 'wb') as picklefile:
    # pickle.dump(classifier,picklefile)

In [11]:
# with open('_vectorizer', 'wb') as picklefile:
   # pickle.dump(vectorizer,picklefile)